added multiple miller-loops, probabilistic and batch verification
zcash/libsnark pull request #9
Opened 2017-01-14 15:22 UTC by arielgabizon

2017-01-16 10:31 UTC, arielgabizon commented
@daira : @ebfull thought that you might want to take a look at the pdf 
https://github.com/arielgabizon/libsnark/blob/batchverification/batchverification.pdf

2017-01-21 01:27 UTC, daira commented
"One can show that a set of valid proofs will always be accepted, and a set of proof of which at least one is non-valid, will be accepted with probability at most 1/s."

Intuitively I would have expected this probability to also depend on the batch size. Why does it not?

2017-01-21 08:07 UTC, arielgabizon commented
Well..first of all where you *do* pay for the batch size is in the time, and number of random bits you need for the test, which grows linearly with the size of the batch.
I'm not sure I have a one sentence intuition.
I think the best way to explain why this probability does not grow with the batch size, is to
go other the addition version of claim 0.1 in words:
Suppose I have a set of Fr a1,..a_t that are not all zero.
For example suppose that the last one  a_t is not zero.
I test whether they are all zero by choosing random coefficients r_1,..,r_t
and checking whether the sum r1*a1+..+r_t*a_t is 0.
The point is, whatever the sum is up to the t-1'th summand, and however large t is;
if a_t is not zero, then the last summand r_t*a_t is completely random in F_r,
so the sum will be completely random  (and therefore the sum will be 0 only with probability 1/r)

2017-01-25 19:14 UTC, zookozcash commented
I'm opposed to replacing the SNARK verifier in production MagicBean.

However, I'm +1 on adding a _redundant_ (ideally parallel, but serial would do for now) SNARK verifier on top of the current verifier.

This is because a bug in the SNARK verifier could have big consequences. There are only a few ways that someone could counterfeit Zcash, i.e. give a payment to an innocent person, so that if the innocent person then spends the money to _another_ innocent person the second innocent person accepts it:

1. They stole all six of the shards from the key generation ceremony. (https://www.youtube.com/watch?v=D6dY-3x3teM)
2. They break the cryptography underlying our current zk-SNARKs. (http://eprint.iacr.org/2013/879, https://eprint.iacr.org/2012/215)
2.b. possibly combined with brute-forcing the elliptic curve we're using (probably takes more than 2^96 computation. One recent analysis by experts suggests that it takes 2^110 work: https://github.com/zcash/zcash/issues/714) 
3. They exploit a vulnerability in the Zcash circuit (https://github.com/zcash/zips/blob/master/protocol/protocol.pdf)
4. They exploit a bug in the SNARK verifier.

These are listed in increasing order of likelihood in my ever-so-humble opinion. I think 4 is a lot more likely than 3, which is a lot more likely than 2, etc.

So, I oppose making any changes to the SNARK verifier unless we have a very good argument that the resulting thing is _safer_ against attack number 4. Redundantly executing both old and new implementations of the verifier would be such an argument. (But we'd have to be very careful about the implementation of the composition itself to avoid that a bug in _that_ accidentally introduces the flaw we're trying to prevent!)

It would also be a good next-step toward a future improvement to the performance of the verification, by getting a new implementation into production and tested. (Note: this kind of testing-in-production does _not_ provide evidence that the new version is immune to malicious attack, but it does provide evidence that the new version doesn't have bugs in the non-malicious case.)

To be clear, I am -10 on a patch which replaces or changes the SNARK verifier, but +1 on a patch that adds a second, redundant SNARK verifier (which slows down performance for now but increases safety). The code that implements the redundancy/composition/serial-or-parallel computation would need to be unit-tested and reviewed carefully to make sure it doesn't introduce any vulnerability.

2017-01-25 19:31 UTC, tromer commented
I agree with @zookozcash 's conservative approach, with this exception:

We should consider using batch-only verification _if and when_ it enables a use case that is otherwise infeasible. And even then, strive to keep the consensus based on the most conservative (unbatched) verifier.

(This is analogous to SPV clients: worse security than full nodes, but they enable new use cases, the damage is bounded, and consensus is not affected.)

2017-01-25 22:05 UTC, zookozcash commented
I really like your perspective in https://github.com/zcash/libsnark/pull/9#issuecomment-275208607, @tromer. Here's another thought: someone could run a service which tests all transactions (including old historical ones from the early days of the blockchain and fresh ones) with all verifiers (including old verifiers that have long-since been phased out of service and new experimental verifiers).

2017-01-25 22:29 UTC, bitcartel commented
The test could also include fuzzing to make sure all verifiers produce the same result.

2017-01-26 05:20 UTC, arielgabizon commented
@bitcartel : What does fuzzing mean?
I want to clarify - this PR *does not change the Zcash verifier at all*. It only adds functionality to the Zcash libsnark fork that can then be used to add a batch verifier to the Zcash code.
I would later do that, for example, by in addition to current verification, to a batch verification every say 100 joinsplits

2017-01-26 18:19 UTC, daira commented
Nitpicking on Zooko's comment:
> 2.b. possibly combined with brute-forcing the elliptic curve we're using (probably takes more than 2^96 computation. One recent analysis by experts suggests that it takes 2^110 work: zcash/zcash#714)

That attack isn't against the elliptic curve, it's against the target group of the pairing G<sub>T</sub>, which is an extension field (and it's not brute force).

2017-01-26 18:22 UTC, daira requested changes

2017-01-26 18:22 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> + * with the price of making the verification procedure probabilisitc, introducing a negligible chance of accepting a bad proofs
"probabilistic", "bad proof"

2017-01-26 18:22 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> + * with the price of making the verification procedure probabilisitc, introducing a negligible chance of accepting a bad proofs
New sentence here.

2017-01-26 18:22 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    // r3Pi_a and vk_A
These comments are copied from ``r1cs_ppzksnark_probabilistic_verifier`` and might not be appropriate for this function.

2017-01-26 18:22 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    pvk.pair1 = ppT::precompute_G2(vk.alphaA_g2);
Missing comment "computing the second input for the first ML factor..".

2017-01-26 18:22 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    //computing the second input for the six ML factor
s/six/sixth/

2017-01-26 18:22 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +        //computing left input for the fifth ML factor
Fix indentation and make line spacing consistent.

2017-01-26 18:22 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    //computing left input for the first ML factor
s/left/first/ for consistency with "second input" in ``r1cs_ppzksnark_processed_batch_verification_key``. (Same change in ``r1cs_ppzksnark_batcher``.)

I considered s/second/right/ instead, but "right" is ambiguous with "correct".

2017-01-27 03:36 UTC, nathan-at-least commented
I'm with Zooko: -10 on switching verifier, +1 with redundancy.

I assume conservative redundancy would be to fail verification if either verifier fails. The simplest composition would be a very small-scoped change to the JoinSplit verification which says something like: ``bool Verify() { return VerifyStandard() && VerifyBatch() }``

We'd be using ``VerifyBatch`` on a single JS at a time, so it would be a redundant security improvement, but we wouldn't gain any performance advantage.

To exercise the batched-nature of batch verification, it could be applied to blocks of transactions at a time in ``CheckBlock``. If done prior to other checks, it would speed up the case of a block containing an invalid proof (or a proof which triggers a bug in batch verification). (Presumably that's a rare case, though. Still, it would be a way to exercise the batch verifier on large batches to learn about its performance and other characteristics.)

2017-01-27 05:30 UTC, arielgabizon commented
A bit of a sidenote, but I'm confused, where is this checkblock method that actually checks joinsplit proofs.
The one here:
https://github.com/zcash/zcash/blob/70db019c6ae989acde0a0affd6a1f1c28ec9a3d2/src/checkpoints.cpp#L27
seems to just check hashes of blocks

2017-01-27 18:14 UTC, arielgabizon commented
Thanks for going over the code and your comments @daira ! I'll revise according to them tomorrow or Monday

2017-01-29 04:28 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    pvk.pair1 = ppT::precompute_G2(vk.alphaA_g2);
done

2017-01-29 04:28 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    //computing the second input for the six ML factor
fixed

2017-01-29 04:29 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +        //computing left input for the fifth ML factor
fixed

2017-01-29 04:29 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    //computing left input for the first ML factor
I think it's fine as is, in this context it's clear right is not correct. Also, I'm using first,second,.. for the ML factors

2017-01-29 04:29 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    // r3Pi_a and vk_A
fixed

2017-02-08 04:59 UTC, arielgabizon commented
Please let me know if there are further requests/comments.
I'd be happy to progress with this PR as only then I can submit the PR adding the batch verifier to the Zcash code (which relies on this new libsnark code)

2017-03-12 19:14 UTC, daira submitted a review, later dismissed
Mostly nits.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
>      //computing left input for the fourth ML factor
I'd still prefer these to say "first" rather than "left".

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
>      //computing left input for the six ML factor
"sixth"

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
>      //computing left input for the fourth ML factor
(similarly in ``r1cs_ppzksnark_probabilistic_verifier``).

2017-03-12 19:14 UTC, daira commented on Makefile
> +
Remove trailing spaces/tabs.

2017-03-12 19:14 UTC, daira commented on Makefile
> -	src/algebra/fields/tests/test_bigint
Keep ``test_bigint``.

2017-03-12 19:14 UTC, daira commented on src/algebra/curves/alt_bn128/alt_bn128_pairing.cpp
> +                                     const alt_bn128_ate_G2_precomp &prec_Q2)
Fix indentation.

2017-03-12 19:14 UTC, daira commented on src/algebra/curves/tests/test_bilinearity.cpp
> +// #endif
It's not necessary to comment this out because ``CURVE_BN128`` is not defined, right? (Ditto for the header inclusion on line 10, and in ``ec_pp.hpp``.)

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/examples/run_r1cs_ppzksnark.tcc
> +                                       const r1cs_primary_input<Fr<ppT> > &primary_input)
Fix indentation.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/examples/run_r1cs_ppzksnark.tcc
> +    r1cs_ppzksnark_proof<ppT> proof = r1cs_ppzksnark_prover<ppT>(keypair.pk, example.primary_input, example.auxiliary_input, example.constraint_system);
Wrap this line.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/examples/run_r1cs_ppzksnark.tcc
> +
Why so many blank lines in this function?

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/examples/run_r1cs_ppzksnark.tcc
> +    //r1cs_ppzksnark_keypair<ppT> keypair = r1cs_ppzksnark_generator<ppT>(example.constraint_system);
Was this supposed to also be testing something else?

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> + * with the price of making the verification procedure probabilistic, introducing a negligible chance of accepting a bad proof.
Technically there's already a negligible chance of unsoundness. Perhaps say "introducing a negligible chance of accepting a proof that would otherwise have been considered bad."

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> + * and the logic behind them are described in  https://github.com/arielgabizon/libsnark/blob/multimiller/src/zk_proof_systems/batchverification.pdf
Change this to ``src/zk_proof_systems/batchverification.pdf`` rather than giving the full URL to your repo. Similarly on lines 490 and 513.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> + * The purpose of this class is to enable one time precomputation of elements that are
one-time

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> +batch_verification_accumulator():pair1(G1<ppT>::zero()),pair2(G1<ppT>::zero()),pair3(G1<ppT>::zero()),pair4(G1<ppT>::zero()),
This would be more readable with the initializers on separate lines.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +/*****Ariel stuff from here ****/
Delete this comment.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +    //computing left input for the first ML factor
But "second input" is already used in ``r1cs_ppzksnark_processed_batch_verification_key``, so there is no consistency at present.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests/test_r1cs_ppzksnark.cpp
> +//****Ariel code-testing batch verifier****///
Remove this comment.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests/test_r1cs_ppzksnark.cpp
> +    //const bool test_serialization = true;
Remove this ^.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests/test_r1cs_ppzksnark.cpp
> +///****End Ariel code ******//////
Remove this comment.

2017-03-12 19:14 UTC, daira commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests/test_r1cs_ppzksnark.cpp
> -    test_r1cs_ppzksnark<default_r1cs_ppzksnark_pp>(1000, 100);
Don't we want to test both the unbatched and batched verification?

2017-03-17 13:57 UTC, arielgabizon commented on Makefile
> +
Done

2017-03-17 13:58 UTC, arielgabizon commented on Makefile
> -	src/algebra/fields/tests/test_bigint
Added

2017-03-17 14:00 UTC, arielgabizon commented on src/algebra/curves/alt_bn128/alt_bn128_pairing.cpp
> +                                     const alt_bn128_ate_G2_precomp &prec_Q2)
Done, I think, not sure how you wanted it

2017-03-17 14:02 UTC, arielgabizon commented on src/algebra/curves/tests/test_bilinearity.cpp
> +// #endif
Removed comment

2017-03-17 14:04 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
> +/*****Ariel stuff from here ****/
Removed

2017-03-17 14:05 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
>      //computing left input for the fourth ML factor
I still disagree

2017-03-17 14:05 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc
>      //computing left input for the six ML factor
Fixed

2017-03-17 14:18 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/examples/run_r1cs_ppzksnark.tcc
> +    r1cs_ppzksnark_proof<ppT> proof = r1cs_ppzksnark_prover<ppT>(keypair.pk, example.primary_input, example.auxiliary_input, example.constraint_system);
Done

2017-03-17 14:19 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/examples/run_r1cs_ppzksnark.tcc
> +                                       const r1cs_primary_input<Fr<ppT> > &primary_input)
Done, I think.

2017-03-17 14:36 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/examples/run_r1cs_ppzksnark.tcc
> +    //r1cs_ppzksnark_keypair<ppT> keypair = r1cs_ppzksnark_generator<ppT>(example.constraint_system);
I don't think so. Deleted commented lines

2017-03-17 14:38 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/examples/run_r1cs_ppzksnark.tcc
> +
Deleted most of them

2017-03-17 14:40 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> + * with the price of making the verification procedure probabilistic, introducing a negligible chance of accepting a bad proof.
I don't follow

2017-03-17 14:41 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> + * and the logic behind them are described in  https://github.com/arielgabizon/libsnark/blob/multimiller/src/zk_proof_systems/batchverification.pdf
changed

2017-03-17 14:43 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.hpp
> +batch_verification_accumulator():pair1(G1<ppT>::zero()),pair2(G1<ppT>::zero()),pair3(G1<ppT>::zero()),pair4(G1<ppT>::zero()),
done.

2017-03-17 14:44 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests/test_r1cs_ppzksnark.cpp
> +//****Ariel code-testing batch verifier****///
removed

2017-03-17 14:44 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests/test_r1cs_ppzksnark.cpp
> +    //const bool test_serialization = true;
removed

2017-03-17 14:44 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests/test_r1cs_ppzksnark.cpp
> +///****End Ariel code ******//////
removed

2017-03-17 14:48 UTC, arielgabizon commented on src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/tests/test_r1cs_ppzksnark.cpp
> -    test_r1cs_ppzksnark<default_r1cs_ppzksnark_pp>(1000, 100);
removed comment from test of unbatched verifier in line 71 of file

2017-03-17 14:50 UTC, arielgabizon commented
@ebfull wanted to run some additional tests, so don't merge yet..

2018-11-13 08:55 UTC, daira commented
Given that Zcash no longer uses libsnark when validating blocks after Sapling activation, I suggest that we close this and reimplement it for the Rust Groth16 verifier.

2023-02-02 10:15 UTC, closed without merging

2023-02-02 10:17 UTC, daira commented
We are no longer maintaining zcash/libsnark; closing all PRs.